places = ["b","ba","ab","ac",]
print (places[0])
print (places[1])
print (places[2])
print (places[3])
black = sorted(places)
print (black)
white = sorted(places,reverse=True)
print (white)
biue = sorted(places,reverse=False)
print (biue)